name: Check Packer Formatting and Validation

on:
 pull_request:
   branches:
    - main
 push:
    branches:
      - main

jobs:
  packer-format-and-validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-packer@main
        with:
          version: 1.9.4

      - run: packer init packer/ami.us-east-1.pkr.hcl

      - name: Check Packer Formatting
        run: |
          echo "Checking Packer file formatting..."
          if packer fmt -check packer/ami.us-east-1.pkr.hcl; then
            echo "Packer file is properly formatted."
          else
            echo "Packer file is not properly formatted. Please run 'packer fmt' to format it."
            exit 1
          fi

      - name: Zip the artifact
        run: |
          zip -r web_app_ami.zip ./
          ls -lrth

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-artifact
          path: webapp.zip    

      - name: Validate Packer Configuration
        run: |
          echo "Validating Packer configuration..."
          if packer validate packer/ami.us-east-1.pkr.hcl; then
            echo "Packer configuration is valid."
          else
            echo "Packer configuration validation failed."
            exit 1
          fi
